language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"
env:
  global:
    - SHA=$(git rev-parse HEAD | cut -c -17)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
  - postgresql
  - docker
install:
  - pip install pipenv
  - pip install coveralls
  - pipenv install

# Run tests
before_script:
  - psql -c "create database $POSTGRES_DB;" -U $POSTGRES_USER
  - psql -c "ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" -U $POSTGRES_USER
  - python manage.py migrate
script:
  - coverage run --source=app manage.py test

  - python -m coverage report -m

deploy:
  on:
    branch: master
  provider: script
  script: bash ./deploy.sh
