# Generated by Django 3.0.5 on 2020-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('O', 'Ok'), ('P', 'Pending'), ('C', 'Cancelled')], default='P', max_length=1)),
            ],
        ),
    ]
